### ISSUE TITLE
Error: Cannot run with sound null safety, because the following dependencies don't support null safety:

### ISSUE THREAD

**Issue by mrtklein** [merlinofcha0s/generator-jhipster-flutter#63]
Hello,

I have created a prototype application "crmsystemtc" with JHipster v7.0.1. Now I wanted to generate a flutter app. Unfortunately I get the following error:

```
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:flutter_bloc
 - package:dart_json_mapper
 - package:bloc
 - package:provider
 - package:formz

For solutions, see https://dart.dev/go/unsound-null-safety
Unhandled exception:
Bad state: Unsupported Null Safety mode NonNullableByDefaultCompiledMode.Invalid, in null.
#0      ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:442:9)
#1      JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:146:33)
#2      FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:638:47)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:549:9)
<asynchronous suspension>
#4      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1119:11)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
Waiting for connection from debug service on Chrome...             15,0s
Failed to compile application.
```

After I run the following command:

`dart pub upgrade --null-safety --dry-run`

Output:
```
Resolving dependencies...
Because reflectable >=2.2.5 <3.0.2 depends on build_runner ^1.10.0 and CrmSystemTc depends on build_runner >=2.0.0, reflectable >=2.2.5 <3.0.2 is forbidden.
So, because CrmSystemTc depends on reflectable 3.0.0-nullsafety.1, version solving failed.
```

I think that the generator does not create runnable code on the current state. How do you recommend to proceed here?

**Comment by baitin** [comment]
dart —no-sound-null-safety run
flutter run —no-sound-null-safety
